name: 'Continuous Integration'

on:
  workflow_dispatch:
  pull_request:

jobs:
  ci:
    name: 'Continuous Integration'
    timeout-minutes: 10

    env:
      VITE_HS_API_KEY: '1234567890-abcd'

    steps:
      - name: ğŸ” Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸŒ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17'

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸ¨ Check code formatting
        run: npm run check:prettier

      - name: âœ¨ Lint and type check the code
        run: npm run lint

      - name: ğŸ—ï¸ Build
        run: NODE_ENV=production npm run build

      - name: ğŸ³ Build docker image
        run: npm run docker:build

